#!/usr/bin/env python3
"""Summarise the private collection as public, aggregate numbers.

The lyrics live in a private repo, but counts are not sensitive: no lyric text,
and by default no titles either. Writes stats.json and rewrites the block
between the stats markers in README.md, so the public repo can show how much
is recorded without exposing what.

  python3 tools/stats.py            # counts only
  python3 tools/stats.py --titles   # also list song titles and artists
"""
import argparse
import json
import re
import sys
from collections import Counter
from datetime import date
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import lyriclib  # noqa: E402

START, END = "<!-- stats:start -->", "<!-- stats:end -->"


def collect(include_titles=False):
    songs, langs, _ = lyriclib.scan()
    ok = [s for s in songs if s.ok]
    registry = langs["languages"]

    originals, all_langs, kinds, tags = Counter(), Counter(), Counter(), Counter()
    files = lines = 0
    for s in ok:
        for lang in s.meta.get("original_languages", []):
            originals[lang] += 1
        for lang in {f["lang"] for f in s.files}:
            all_langs[lang] += 1
        for f in s.files:
            kinds[f["kind"]] += 1
            files += 1
            secs = lyriclib.parse_sections((s.path / f["file"]).read_text("utf-8"))
            lines += sum(len(x["lines"]) for x in secs)
        for t in s.meta.get("tags", []):
            tags[t] += 1

    def label(code):
        e = registry.get(code, {})
        return e.get("endonym") or e.get("label") or code

    data = {
        "updated": date.today().isoformat(),
        "songs": len(ok),
        "lyric_files": files,
        "lines": lines,
        "original_languages": {label(c): n for c, n in originals.most_common()},
        "languages_present": {label(c): n for c, n in all_langs.most_common()},
        "versions_by_kind": dict(kinds.most_common()),
        "tags": dict(tags.most_common()),
    }
    if include_titles:
        data["titles"] = [
            {"title": lyriclib.display_title(s),
             "artist": " · ".join(a.get("name", "") for a in s.meta.get("artist", []))}
            for s in ok
        ]
    return data


def render(d):
    def row(m):
        return " · ".join(f"{k} {v}" for k, v in m.items()) or "—"
    out = [
        f"**{d['songs']} songs · {d['lyric_files']} lyric files · {d['lines']:,} lines**",
        "",
        f"| | |",
        f"|---|---|",
        f"| written in | {row(d['original_languages'])} |",
        f"| languages present | {row(d['languages_present'])} |",
        f"| versions | {row(d['versions_by_kind'])} |",
        f"| tags | {row(d['tags'])} |",
        "",
        f"<sub>Generated by `tools/stats.py` on {d['updated']}. "
        f"The lyrics themselves live in a private repo.</sub>",
    ]
    return "\n".join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--titles", action="store_true", help="also record song titles")
    args = ap.parse_args()

    d = collect(args.titles)
    (lyriclib.ROOT / "stats.json").write_text(
        json.dumps(d, ensure_ascii=False, indent=2) + "\n", "utf-8")

    readme = lyriclib.ROOT / "README.md"
    text = readme.read_text("utf-8")
    block = f"{START}\n{render(d)}\n{END}"
    if START in text and END in text:
        text = re.sub(re.escape(START) + r".*?" + re.escape(END), block, text, flags=re.S)
    else:
        text = text.rstrip("\n") + "\n\n## Collection\n\n" + block + "\n"
    readme.write_text(text, "utf-8")

    print(f"  wrote  stats.json + README block  "
          f"({d['songs']} songs, {d['lyric_files']} files, {d['lines']:,} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
